# Generated by Django 6.1 on 2026-08-15 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('inventory_level', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('weather_condition', models.CharField(max_length=50)),
                ('holiday_promotion', models.BooleanField(default=False)),
                ('competitor_pricing', models.FloatField(default=0)),
                ('seasonality', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.store')),
            ],
            options={
                'ordering': ['product_id'],
                'constraints': [models.UniqueConstraint(fields=('store', 'product_id'), name='unique_product_per_store')],
            },
        ),
    ]
