# Generated by Django 6.1 on 2026-08-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='predicted_demand',
            field=models.FloatField(default=0),
        ),
    ]
