# Generated by Django 6.1 on 2026-08-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_predicted_demand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='predicted_demand',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
